/*
 * generated by Xtext 2.12.0
 */
package de.hs_coburg.mgse.platform.curriculum.ide


/**
 * Use this class to register ide components.
 */
class CurriculumModelIdeModule extends AbstractCurriculumModelIdeModule {
}
