/*
 * generated by Xtext 2.12.0
 */
package de.hs_coburg.mgse.platform.glossary.tests

import com.google.inject.Inject
import de.hs_coburg.mgse.platform.glossary.glossaryModel.Glossary
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(GlossaryModelInjectorProvider)
class GlossaryModelParsingTest {
	@Inject
	ParseHelper<Glossary> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Glossar Begriffe
			
			Sektion "Abschlüsse"
				[Master_of_Science]
				Wort: "Master of Science"
				Bedeutung: "Masterabschluss eines naturwissenschaftlichen Studienganges"
				Abkuerzung: "M.Sc."
				
				[Master_of_Arts]
				Wort: "Master of Arts"
				Bedeutung: "Masterabschluss eines geistes-, kultur-, sozial- oder wirtschaftswissenschaftlichen Studienganges"
				Abkuerzung: "M.A."
				
				[Master_of_BA]
				Wort: "Master of Business Administration"
				Bedeutung: "Masterabschluss eines Studienganges, welcher hauptsächlich Managementkompetenzen vermittelt."
				Abkuerzung: "MBA"
					
				[Bachelor_of_Science]
				Wort: "Bachelor of Science"
				Bedeutung: "Bachelorabschluss eines naturwissenschaftlichen Studienganges"
				Abkuerzung: "B.Sc."
			Ende
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
