/*
 * generated by Xtext 2.12.0
 */
package de.hs_coburg.mgse.platform.glossary.validation

import de.hs_coburg.mgse.platform.glossary.glossaryModel.Glossary
import de.hs_coburg.mgse.platform.glossary.glossaryModel.GlossaryEntry
import de.hs_coburg.mgse.platform.glossary.glossaryModel.GlossaryModelPackage
import java.util.LinkedList
import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.validation.CheckType

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class GlossaryModelValidator extends AbstractGlossaryModelValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					GlossaryModelPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

@Check(CheckType.FAST)
	def checkAbbreviations(Glossary glossary){
		val entries = getAllEntries(glossary)
		val abbreviations = entries.map[e | e.information.abbreviation]
		for(var i = 0; i<entries.length; i++){
			val currentEntry = entries.get(i)
			val currentAbbreviation = currentEntry.information.abbreviation
			if(abbreviations.filter[it == currentAbbreviation].size > 1){
				error('Duplicate Abbreviation', currentEntry.information, GlossaryModelPackage.Literals.GLOSSARY_ENTRY_INFORMATION__ABBREVIATION)
			}
		}
	}
	
	@Check(CheckType.FAST)
	def checkWords(Glossary glossary){
		val entries = getAllEntries(glossary)
		val words = entries.map[e | e.information.word]
		for(var i = 0; i<entries.length; i++){
			val currentEntry = entries.get(i)
			val currentWord = currentEntry.information.word
			if(words.filter[it == currentWord].size > 1){
				error('Duplicate Word', currentEntry.information, GlossaryModelPackage.Literals.GLOSSARY_ENTRY_INFORMATION__WORD)
			}
			if(currentWord.isEmpty){
				error('Word should not be empty', currentEntry.information, GlossaryModelPackage.Literals.GLOSSARY_ENTRY_INFORMATION__WORD)
			}
		}
	}
	
	@Check(CheckType.FAST)
	def checkEntryNames(Glossary glossary){
		val entries = getAllEntries(glossary)
		for(var i = 0; i<entries.length; i++){
			val currentEntry = entries.get(i)
			if(entries.filter[it.name == currentEntry.name].size > 1){
				error('Duplicate Entry ID', currentEntry, GlossaryModelPackage.Literals.GLOSSARY_ENTRY__NAME)
			}
		}
	}
	
	def getAllEntries(Glossary glossary){
		val entries = new LinkedList<GlossaryEntry>
		glossary.sections.forEach[section | entries.addAll(section.entries)]
		return entries
	}
	
}
