/*
 * generated by Xtext 2.12.0
 */
package de.hs_coburg.mgse.platform.course.ide


/**
 * Use this class to register ide components.
 */
class CourseModelIdeModule extends AbstractCourseModelIdeModule {
}
