/*
 * generated by Xtext 2.12.0
 */
package de.hs_coburg.mgse.platform.glossary.ide


/**
 * Use this class to register ide components.
 */
class GlossaryModelIdeModule extends AbstractGlossaryModelIdeModule {
}
