/*
 * generated by Xtext 2.12.0
 */
package de.hs_coburg.mgse.platform.ser


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SERModelRuntimeModule extends AbstractSERModelRuntimeModule {
}
