/*
 * generated by Xtext 2.12.0
 */
package de.hs_coburg.mgse.platform.ser


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SERModelStandaloneSetup extends SERModelStandaloneSetupGenerated {

	def static void doSetup() {
		new SERModelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
