/*
 * generated by Xtext 2.12.0
 */
package de.hs_coburg.mgse.platform.curriculum


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CurriculumModelStandaloneSetup extends CurriculumModelStandaloneSetupGenerated {

	def static void doSetup() {
		new CurriculumModelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
