/*
 * generated by Xtext 2.12.0
 */
package de.hs_coburg.mgse.platform.course


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CourseModelStandaloneSetup extends CourseModelStandaloneSetupGenerated {

	def static void doSetup() {
		new CourseModelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
